### ISSUE TITLE
iLo discovery powershell cmdlet - requests.psm1 error

### ISSUE THREAD

**Issue by miroberts** [OneIdentity/safeguard-discovery#12]
TFS # is 387759

Issue has been detected when following test steps of the following test case:
[263155 - iLo discovery powershell cmdlet](https://dev.azure.com/1id/Safeguard%20Privileged%20Passwords/_workitems/edit/263155)

Test case steps:
Go to https://github.com/OneIdentity/safeguard-discovery and follow the instructions to get everything setup.
Run attached script iLodiscovery.ps1.
When running the script, Line 33 (#$acctobj.AllowPasswordRequest = 'True') can be commented out to avoid the following error:
Exception setting "AllowPasswordRequest": "The property 'AllowPasswordRequest' cannot be found on this object. Verify that the property exists and can be set."
This error does not stop the script from running.​

When the script is executed and all steps of the cmdlet are completed, it throws an error and fails; the cleanup process does not take place.

Checkout the Passwords
Found  requestable accounts matching 'Administrator'
At C:\Users\cigdem\Documents\WindowsPowerShell\Modules\safeguard-ps\7.1.76987\requests.psm1:104 char:13
+             throw "Found $($local:Accounts.Count) requestable account ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Found  requesta...'Administrator':String) [], RuntimeException
    + FullyQualifiedErrorId : Found  requestable accounts matching 'Administrator'

![image](https://user-images.githubusercontent.com/32682052/204379109-adc85a09-67f9-4085-af51-e38f81a186b9.png)

The same issue also occurs for another script (postgresdiscovery.ps1) listed in test case [263159 - postgres discovery powershell cmdlet](https://dev.azure.com/1id/Safeguard%20Privileged%20Passwords/_workitems/edit/263159).

**Comment by MichaelThompson** [comment]
I tweaked the test to run against my appliance and it runs just great. I had no problem with it. If you find out more concerning this error please update this issue.
