### ISSUE TITLE
postgres discovery script - requests.psm1 error

### ISSUE THREAD

**Issue by miroberts** [OneIdentity/safeguard-discovery#13]
TFS # 387760

​Issue has been detected when following test steps of the following test case:
[263159 - postgres discovery powershell cmdlet](https://dev.azure.com/1id/Safeguard%20Privileged%20Passwords/_workitems/edit/263159).

Test case steps:
Go to https://github.com/OneIdentity/safeguard-discovery and follow the instructions to get everything setup.
Run attached script postgresdiscovery.ps1.
When running the script, Line 33 (#$acctobj.AllowPasswordRequest = 'True') can be commented out to avoid the following error:
Exception setting "AllowPasswordRequest": "The property 'AllowPasswordRequest' cannot be found on this object. Verify that the property exists and can be set."
This error does not stop the script from running.​

When the script is executed and all steps of the cmdlet are completed, it throws an error and fails; the cleanup process does not take place.

Checkout the Passwords
Found  requestable accounts matching 'postgres'
At C:\Users\cigdem\Documents\WindowsPowerShell\Modules\safeguard-ps\7.1.76987\requests.psm1:104 char:13
+             throw "Found $($local:Accounts.Count) requestable account ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Found  requesta...hing 'postgres':String) [], RuntimeException
    + FullyQualifiedErrorId : Found  requestable accounts matching 'postgres'

![image](https://user-images.githubusercontent.com/32682052/204379798-89c669e9-97df-40f5-8ede-b198ac56f42a.png)

The same issue also occurs for another script (iLodiscovery.ps1) listed in test case [263155 - iLo discovery powershell cmdlet](https://dev.azure.com/1id/Safeguard%20Privileged%20Passwords/_workitems/edit/263155). Check bug [387759](https://dev.azure.com/1id/Safeguard%20Privileged%20Passwords/_workitems/edit/387759) for further details.

**Comment by MichaelThompson** [comment]
I ran through your test -- tweaked it to run against v4 -- and it worked just fine. I had no issues. Also, the error that you have in your screenshot is not from this powershell module anyway. It seems this bug is not applicable. Feel free to add more info.
